### ISSUE TITLE
A249 賴芊卉 A88181/B深灰 貨品瑕疵換貨處理中!!

### ISSUE THREAD

**Issue by purplekelly22** [kevinyu75/Kaiwencreative#14]
目前商品已退回，與廠商換貨中 !!!!!!!!!!!!!!!
有任何進度請更新 !!!!!!!!!!!!!!!!!
![image](https://user-images.githubusercontent.com/43432807/46068850-b204e100-c1ac-11e8-86f2-a3bcfb530b61.png)

**Comment by jih0717** [comment]
10/11目前已到貨。

**Comment by kevinyu75** [comment]
顧客已取
