### ISSUE TITLE
蜜蠟刮痧梳 H88096 [現貨銷售]

### ISSUE THREAD

**Issue by purplekelly22** [kevinyu75/Kaiwencreative#23]
較多的現貨，將於文章下方通知現貨商品
較少的現貨，放於現貨專區
任何於Line貨FB上確認賣出的現貨
煩請當事人成立訂單並將狀態直接更新為"已到貨"
現場的現貨處理Kelly會自行成立 =)
========================================
蜜蠟刮痧梳 H88096
每個 * 9
![image](https://user-images.githubusercontent.com/43432807/46241582-87a26600-c3ee-11e8-9846-02ae3436aa9e.png)

**Comment by purplekelly22** [comment]
9/29 13:50 -3 by Hoho

**Comment by hoho1405** [comment]
9/29 14:02-1  by hoho
