### ISSUE TITLE
日系水晶女玻璃絲短襪(五雙一組) H87264

### ISSUE THREAD

**Issue by purplekelly22** [kevinyu75/Kaiwencreative#25]
H廠此件商品過久未到，近期也只來一組，請協助追貨品 !!!!!!!!!!!!!!!

![image](https://user-images.githubusercontent.com/43432807/46405455-de83a480-c73a-11e8-94c8-1a22e5b869ec.png)

![image](https://user-images.githubusercontent.com/43432807/46405493-0541db00-c73b-11e8-8a3c-667feb0e0701.png)

**Comment by kevinyu75** [comment]
皆已到貨，已解決～～
